-- MySQL Script generated by MySQL Workbench
-- Sun Feb 16 22:34:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema edziennik
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edziennik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edziennik` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `edziennik` ;

-- -----------------------------------------------------
-- Table `edziennik`.`przedmioty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edziennik`.`przedmioty` (
  `id_przedmiot` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_przedmiot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edziennik`.`nauczyciele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edziennik`.`nauczyciele` (
  `id_nauczyciel` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(60) NOT NULL,
  `typ` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_nauczyciel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edziennik`.`kursy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edziennik`.`kursy` (
  `id_kurs` INT NOT NULL AUTO_INCREMENT,
  `id_nauczyciel` INT NOT NULL,
  `id_przedmiot` INT NOT NULL,
  `nazwa` VARCHAR(45) NOT NULL,
  `data_rozpoczecia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_kurs`),
  INDEX `fk_przedmioty_nauczycieli_nauczyciele_idx` (`id_nauczyciel` ASC),
  INDEX `fk_przedmioty_nauczycieli_przedmioty1_idx` (`id_przedmiot` ASC),
  CONSTRAINT `fk_przedmioty_nauczycieli_nauczyciele`
    FOREIGN KEY (`id_nauczyciel`)
    REFERENCES `edziennik`.`nauczyciele` (`id_nauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_przedmioty_nauczycieli_przedmioty1`
    FOREIGN KEY (`id_przedmiot`)
    REFERENCES `edziennik`.`przedmioty` (`id_przedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edziennik`.`uczeniowie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edziennik`.`uczeniowie` (
  `id_uczen` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `id_kurs` INT NOT NULL,
  PRIMARY KEY (`id_uczen`),
  INDEX `fk_uczen_kurs1_idx` (`id_kurs` ASC),
  CONSTRAINT `fk_uczen_kurs1`
    FOREIGN KEY (`id_kurs`)
    REFERENCES `edziennik`.`kursy` (`id_kurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edziennik`.`zajecia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edziennik`.`zajecia` (
  `id_zajecia` INT NOT NULL AUTO_INCREMENT,
  `id_kurs` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_zajecia`),
  INDEX `fk_zajecia_kurs1_idx` (`id_kurs` ASC),
  CONSTRAINT `fk_zajecia_kurs1`
    FOREIGN KEY (`id_kurs`)
    REFERENCES `edziennik`.`kursy` (`id_kurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edziennik`.`obecnosci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edziennik`.`obecnosci` (
  `id_obecnosc` INT NOT NULL AUTO_INCREMENT,
  `id_uczen` INT NOT NULL,
  `id_zajecia` INT NOT NULL,
  `obecnosc` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_obecnosc`),
  INDEX `fk_obecnosci_uczen1_idx` (`id_uczen` ASC),
  INDEX `fk_obecnosci_zajecia1_idx` (`id_zajecia` ASC),
  CONSTRAINT `fk_obecnosci_uczen1`
    FOREIGN KEY (`id_uczen`)
    REFERENCES `edziennik`.`uczeniowie` (`id_uczen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obecnosci_zajecia1`
    FOREIGN KEY (`id_zajecia`)
    REFERENCES `edziennik`.`zajecia` (`id_zajecia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edziennik`.`oceny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edziennik`.`oceny` (
  `id_oceny` INT NOT NULL AUTO_INCREMENT,
  `ocena` VARCHAR(1) NOT NULL,
  `id_zajecia` INT NOT NULL,
  `forma` VARCHAR(45) NOT NULL,
  `waga` VARCHAR(2) NOT NULL,
  `id_uczen` INT NOT NULL,
  PRIMARY KEY (`id_oceny`),
  INDEX `fk_oceny_zajecia1_idx` (`id_zajecia` ASC),
  INDEX `fk_oceny_uczen1_idx` (`id_uczen` ASC),
  CONSTRAINT `fk_oceny_zajecia1`
    FOREIGN KEY (`id_zajecia`)
    REFERENCES `edziennik`.`zajecia` (`id_zajecia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oceny_uczen1`
    FOREIGN KEY (`id_uczen`)
    REFERENCES `edziennik`.`uczeniowie` (`id_uczen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
